### ISSUE TITLE
Input customization

### ISSUE THREAD

**Issue by lexlexa** [react-component/picker#103]
Add prop to customize input fields.

Example 

```jsx
<Picker inputRender={field => <div>{field}</div>}  />
```

Case example: Add mask

**Comment by Vincz** [comment]
Hi guys! I would also like to be able to customise the underlaying input. The way @lexlexa suggest would be fine, or an additional parameters with input props would be fine to. 

Thanks!

**Comment by MakaryHryshkin** [comment]
Hey guys! I also would like a way to customize input, my use case is simple - I want to prevent letter typing. It will be a bit more complicated than the example in the issue as the user has to be responsible for rendering props `inputRender` provides. Would be happy to create a PR for this!

**Comment by mhryshkin** [comment]
@lexlexa  @Vincz Does the PR I've opened something that you guys were talking about? Let's push it to be merged :smiley:

**Comment by Vincz** [comment]
Hey @mhryshkin! Thank you for this PR. If I remember correctly, my use case was the same as @lexlexa 
I wanted to add a react-mask on the input. From what I understand from your PR, it would be fine as it would allow a total control on the rendered input. Fine by me then! Thanks again!

**Comment by vojtechportes** [comment]
Any chance this will be merged anytime soon?

**Comment by evankazadaiev** [comment]
It's been a while since the PR was opened, it solves my issue.
Any chance it's going to be reviewed and merged?

**Comment by MakaryHryshkin** [comment]
@evankazadaiev I don't believe it will be merged =(

**Comment by Plumbiu** [comment]
> > Add prop to customize input fields.
> > Example
> > ```js
> > <Picker inputRender={field => <div>{field}</div>}  />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Case example: Add mask
> 
> pls add this feature to RangePicker too Works only for Picker now

I also want this feature to RangePicker
