### ISSUE TITLE
Missing getShortWeekdays and getShortMonths for date-fns

### ISSUE THREAD

**Issue by fgblomqvist** [react-component/picker#128]
I just switched to date-fns and this is what my antd datepicker looks like:
![Screen Shot 2020-08-14 at 10 14 17 AM](https://user-images.githubusercontent.com/649260/90258714-ef150380-de16-11ea-865e-a8f416814e6c.png)

This is what it looked like before the switch (was using Dayjs):
![Screen Shot 2020-08-14 at 10 14 52 AM](https://user-images.githubusercontent.com/649260/90258766-ffc57980-de16-11ea-9673-e44c1433eb7d.png)

This is how I generate the picker:
```ts
import generatePicker from 'antd/es/date-picker/generatePicker';
import dateFnsGenerateConfig from 'rc-picker/lib/generate/dateFns';

export default generatePicker<Date>(dateFnsGenerateConfig);
```

And here's an example of how I render it:
```jsx
      <DatePicker.RangePicker
        bordered={false}
        onChange={dates => {
          this.setDates(dates || [null, null]);
        }}
        placeholder={['Start', 'End']}
        value={[minDate, maxDate]}
      />
```

Looks like the config for date-fns that's generated by rc-picker is missing the methods `getShortWeekdays` and `getShortMonths`.

I am using date-fns 2.15.0. I tried both rc-picker 1.15.3 and 2.0.5 but both gave the same (broken) results.

**Comment by fgblomqvist** [comment]
To clarify: I switched away from dayjs at the same time.

**Comment by fgblomqvist** [comment]
As pointed out [here](https://github.com/ant-design/ant-design/issues/26045#issuecomment-675226218), the issue is that rc-picker does not implement `getShortWeekdays` and `getShortMonths` in [the config generator for date-fns](https://github.com/react-component/picker/blob/master/src/generate/dateFns.ts).

Is this something that is planned? Are you looking for contributions?

**Comment by fgblomqvist** [comment]
This is the solution I went with:

```ts
import generatePicker from 'antd/es/date-picker/generatePicker';
import { enUS } from 'date-fns/locale';
import dateFnsGenerateConfig from 'rc-picker/lib/generate/dateFns';

const locales: Record<string, Locale> = { en_US: enUS };

const originFormat = dateFnsGenerateConfig.locale.format;
Object.assign(dateFnsGenerateConfig.locale, {
  format: (local: string, date: Date, format: string) => {
    if (/\[.+]/.test(format)) {
      const f = format.replace(/[[\]]/g, "'");
      return originFormat(local, date, f);
    }
    return originFormat(local, date, format);
  },

  getShortMonths: (locale: string) => {
    const loc = locales[locale];
    if (!loc || !loc.localize) return [];

    return Array.from(Array(12).keys()).map(i =>
      loc.localize!.month(i, { width: 'abbreviated' }),
    );
  },

  getShortWeekDays: (locale: string) => {
    const loc = locales[locale];
    if (!loc || !loc.localize) return [];

    return Array.from(Array(7).keys()).map(i =>
      loc.localize!.day(i, { width: 'short' }),
    );
  },
});

export default generatePicker<Date>(dateFnsGenerateConfig);
```

It replicates the Dayjs behavior. That code should be good enough to add to rc-picker I think. The way it would be incorporated is that `generatePicker` would take a second argument, a map from `ISO639-1_ISO3166` (e.g. `en_US`) to a locale. Any locale you want to support in your app, you will need to import and add to that map (this is to optimize bundle size). Let me know if you'd accept a PR with this.

**Comment by fgblomqvist** [comment]
lol and all this time there were already two PRs open:
https://github.com/react-component/picker/pull/115
https://github.com/react-component/picker/pull/126
😞

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/picker/pull/115
