### ISSUE TITLE
基于antd 4.x 封装组件库时报错 Invalid hook call. 

### ISSUE THREAD

**Issue by yjzzcao** [react-component/picker#130]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
1. 利用lerna管理前端模块
```txt
root/
  ├── packages/
      ├── ui/
          ├── package.json
      ├── fe/
          ├── package.json
```
```json
// root/packages/ui/package.json
{
  ...
  "name": "my-ui",
  "version": "0.0.0",
  "peerDependencies": {
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  },
  ...
}
```
```json
// root/packages/fe/package.json
{
  ...
  "dependencies": {
    "my-ui": "^0.0.0",
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  },
  ...
}
```
2. 运行项目时 报错 Invalid hook call.
3. 通过 npm ls react 发现 react 被 rc-picker 依赖进来
```bash
> root/packages/ui $ npm ls react
@gogoal/lts-probe-ui@0.0.0 /Users/caoyujian/workspace/lts-probe/packages/lts-probe-ui
└─┬ antd@4.5.4
  └─┬ rc-picker@1.15.3
    └── react@16.13.1 
```

### What is expected?
rc-picker 中的 react 依赖从 dependencies 移动至 devDependencies

### What is actually happening?
运行项目时 报错 Invalid hook call.

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | ^16.9.0 |
| System | Mac |
| Browser | Chrome latest |

**Comment by yjzzcao** [comment]
#116 相同问题

**Comment by afc163** [comment]
fixed in https://github.com/react-component/picker/commit/3192f50504aa6aadc2b31aecf6289fe18ff5176d
