### ISSUE TITLE
generateConfig for date-fns throws error for some locales

### ISSUE THREAD

**Issue by StefanoMagrassi** [react-component/picker#147]
The `generateConfig` methods use [`dealLocal()`](https://github.com/react-component/picker/blob/master/src/generate/dateFns.ts#L27) function to get `date-fns` specific locale data for the provided language, but the implementation fails in some cases because `rc-picker` locales names **do not exactly match** with `date-fns` ones.

For example Italian:
- `rc-picker` use [`it_IT`](https://github.com/react-component/picker/blob/master/src/locale/it_IT.ts#L4) as locale name;
- `dealLocal()` converts it into `itIT`;
- `generateConfig.getWeekFirstDay()` method [tries to load](https://github.com/react-component/picker/blob/master/src/generate/dateFns.ts#L68) `date-fns` locale data with an `itIT` key, but [**it does not exists**](https://github.com/date-fns/date-fns/blob/master/src/locale/index.js#L42) and this leads to `clone` constant to be `undefined`.

The only solution is to replace the current `dealLocal()` implementation with a static map of locales names and prevent errors with a default value:
```ts
const DEFAULT_LOCALE = 'enUS';

const LOCALES_MAP = {
  'en_US': 'enUS',
  'it_IT': 'it',
  'es_ES': 'es',

  // and so on...
}

const dealLocal = (str: string): string => LOCALES_MAP[str] || DEFAULT_LOCALE;
```

**Comment by stepanzin** [comment]
Same problem with ru_RU locale

**Comment by Roguehp98** [comment]
Same problem with de, fr locale

**Comment by zombieJ** [comment]
Hi, guys. Could you help to send PR about this?

**Comment by Saarnaki** [comment]
@zombieJ are there any issues regarding spawnia's PR?

**Comment by dingram94** [comment]
Is there any way we can finally fix this after 2 years? German is still not working like other languages too...

**Comment by spawnia** [comment]
> Is there any way we can finally fix this after 2 years? German is still not working like other languages too...

Yup, merging https://github.com/react-component/picker/pull/289 or implementing https://github.com/react-component/picker/pull/289#issuecomment-1063640635 would do it.

**Comment by dingram94** [comment]
@spawnia That is what I was asking for 🥲
