### ISSUE TITLE
Controlled Open - Is it possible to close when clickoutside, but not close after selecting the range in RangePicker ?

### ISSUE THREAD

**Issue by chienweiluo** [react-component/picker#172]
### Reproduction link

https://codesandbox.io/s/rc-picker-playground-forked-mp6bv?file=/src/App.tsx

### What is expected?

When I do click-outside may close the popup too.

### Version

Environment | Info
-- | --
React | 16.8.0
rc-picker | ^1.6.1

### Related Issue

Same feature.
https://github.com/ant-design/ant-design/issues/24083

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/24083#issuecomment-1316680387
