### ISSUE TITLE
Dayjs is not peer dependency anymore, breaks registration of plugins in client app that has also the dependency

### ISSUE THREAD

**Issue by sanderdewilde** [react-component/picker#329]
Hi,

We have a design system library we use to support our applications. This library uses ant which uses rc-picker. We re-generate the pickers using ant, with dayjs instead of moment. In this library, we mark dayjs as a peer dependency. We also install it in our main applications where we register multiple plugins on the singleton dayjs instance. This has been made possible through https://github.com/react-component/picker/pull/214.

However, since https://github.com/react-component/picker/pull/270 our workflow has been broken. Since dayjs is included as a dependency here, the build of our design system library causes a dayjs singleton to be created, as does our main app. Therefore we have two singletons, and the plugins are only registered on one of them.

**Comment by sanderdewilde** [comment]
I was able to work around the problem by using webpack aliasing as described here: https://blog.maximeheckel.com/posts/duplicate-dependencies-npm-link/.

I stumbled upon this by upgrading my npm version to 7+, since npm7, peerDeps are also automatically installed which caused the same problem to appear even without the changes of #270.

**Comment by deathemperor** [comment]
Got the same issue, fix it with yarn `resolutions` config for anyone googling this
