### ISSUE TITLE
DatePicker not working with React 18

### ISSUE THREAD

**Issue by shadoworion** [react-component/picker#371]
Datepicker freeze UI on open

Environment:
Vite 2.9.1
React 18.0.0

I think it is also a problem with all RC components with a dropdown like select or cascader

**Comment by janickvwcotiss** [comment]
Anyone got any updates on this? Getting the same error of the datetime picker freezing on open. Anyone got it working with react 18?

**Comment by rrmdn** [comment]
@janickvwcotiss came across the same problem with react 18, solved by purging my `yarn.lock` as mentioned here https://github.com/ant-design/ant-design/issues/34890
