### ISSUE TITLE
v3.1.5 npm包中没有es目录

### ISSUE THREAD

**Issue by baicoding** [react-component/picker#582]
![image](https://user-images.githubusercontent.com/29280682/218104167-63bbcdcf-1efc-4575-b7ed-22037ab1cb96.png)
如图，3.1.4下是正常的。

**Comment by afc163** [comment]
https://unpkg.com/browse/rc-picker@3.1.5/ 有的。

**Comment by baicoding** [comment]
刚才更新的确有了
