### ISSUE TITLE
antd: 4.24.8,     rc-picker 2.7.1  error TS TS1005

### ISSUE THREAD

**Issue by blackshh** [react-component/picker#623]
use:  antd: 4.24.8,     rc-picker 2.7.1

error 👍 /node_modules/_rc-picker@2.7.1@rc-picker/lib/PickerPanel.d.ts(12,15): error TS1005: ',' expected.

![image](https://user-images.githubusercontent.com/20354890/233566498-4dbfd9ed-8c7b-4750-82f6-35c98e22ada5.png)

**Comment by pulo** [comment]
+1

**Comment by yoyo837** [comment]
Close by #624
